name: Bb tests
on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          bb: latest
      - uses: actions/cache@v4
        id: cache-deps
        with:
          path: ~/.m2/repository
          key: deps-${{ hashFiles('bb.edn') }}-${{ hashFiles('deps.edn') }}
          restore-keys: deps-
      - run: |
          bb test:bb
          bb test:bb-smoke-test
          
